/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shoessys.ui;

import AppPackage.AnimationClass;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author trann
 */
public class ChaoJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ChaoJDialog
     */
    public ChaoJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLeft = new javax.swing.JLabel();
        lblTop = new javax.swing.JLabel();
        lblRight = new javax.swing.JLabel();
        lblBottom = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        pnlWelcome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/bee1.png"))); // NOI18N
        getContentPane().add(lblLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/bee2.png"))); // NOI18N
        getContentPane().add(lblTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/bee3.png"))); // NOI18N
        getContentPane().add(lblRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 0, -1, -1));

        lblBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/bee4.png"))); // NOI18N
        getContentPane().add(lblBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        progressBar.setStringPainted(true);
        getContentPane().add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 343, 551, -1));

        pnlWelcome.setBackground(new java.awt.Color(255, 255, 255));
        pnlWelcome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel1.setFont(new java.awt.Font("Vladimir Script", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/welcome_550_340.gif"))); // NOI18N

        javax.swing.GroupLayout pnlWelcomeLayout = new javax.swing.GroupLayout(pnlWelcome);
        pnlWelcome.setLayout(pnlWelcomeLayout);
        pnlWelcomeLayout.setHorizontalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlWelcomeLayout.setVerticalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(pnlWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 552, 341));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChaoJDialog dialog = new ChaoJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBottom;
    private javax.swing.JLabel lblLeft;
    private javax.swing.JLabel lblRight;
    private javax.swing.JLabel lblTop;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

    private void init() {
        setLocationRelativeTo(null);
        
        new Thread(){
            public void run(){
                try {
//                    Thread.sleep(100);
                    pnlWelcome.setVisible(false);
                    AnimationClass ani = new AnimationClass();
                    ani.jLabelXLeft(lblLeft.getX(), -1000, 3, 1, lblLeft);
                    ani.jLabelYUp(lblTop.getY(), -1000, 5, 1, lblTop);
                    ani.jLabelXRight(lblRight.getX(), 1000, 3, 1, lblRight);
                    ani.jLabelYDown(lblBottom.getY(), 1000, 5, 1, lblBottom);
                    pnlWelcome.setVisible(true);
                } catch (Exception e) {}
            }
        }.start();
       
        new Thread(){
            @Override
            public void run(){
                try {
                    pnlWelcome.setVisible(true);
                    Thread.sleep(1000);
                } catch (Exception e) {}
                new Timer(50, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        int value = progressBar.getValue();
                        if(value < progressBar.getMaximum()){
                            progressBar.setValue(value+1);
                        }else{
                            ChaoJDialog.this.dispose();
                        }
                    }
                }).start();
            }
        }.start();
    }
}
