/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shoessys.ui;

import com.shoessys.ultil.Auth;
import com.shoessys.ultil.MsgBox;
import com.shoessys.ultil.Ximage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author trann
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.init();
    }

    public static void processLoginSuccessful() {
        lblTaiKhoan.setText(Auth.User.getTenNV());
        lblEmail.setText(Auth.User.getEmail());
        Ximage.getImageRound(Auth.User.getHinh(), 64, 64, "nhanvien", lblHinh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        lblHinh = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlDonHang = new javax.swing.JPanel();
        pnlColorDH = new javax.swing.JPanel();
        lblIconDH = new javax.swing.JLabel();
        lblTextDH = new javax.swing.JLabel();
        lblIconDH1 = new javax.swing.JLabel();
        pnlLoai = new javax.swing.JPanel();
        pnlColorL = new javax.swing.JPanel();
        lblIconL = new javax.swing.JLabel();
        lblTextL = new javax.swing.JLabel();
        lblIconL1 = new javax.swing.JLabel();
        pnlNhaCC = new javax.swing.JPanel();
        pnlColorNCC = new javax.swing.JPanel();
        lblIconNCC = new javax.swing.JLabel();
        lblTextNCC = new javax.swing.JLabel();
        lblIconNCC1 = new javax.swing.JLabel();
        pnlSanPham = new javax.swing.JPanel();
        pnlColorSP = new javax.swing.JPanel();
        lblIconSP = new javax.swing.JLabel();
        lblTextSP = new javax.swing.JLabel();
        lblIconSP1 = new javax.swing.JLabel();
        pnlKhachHang = new javax.swing.JPanel();
        pnlColorKH = new javax.swing.JPanel();
        lblIconKH = new javax.swing.JLabel();
        lblTextKH = new javax.swing.JLabel();
        lblIconKH1 = new javax.swing.JLabel();
        pnlNhanVien = new javax.swing.JPanel();
        pnlColorNV = new javax.swing.JPanel();
        lblIconNV = new javax.swing.JLabel();
        lblTextNV = new javax.swing.JLabel();
        lblIconNV1 = new javax.swing.JLabel();
        pnlThonhKe = new javax.swing.JPanel();
        pnlColorTK = new javax.swing.JPanel();
        lblIconTK = new javax.swing.JLabel();
        lblTextTK = new javax.swing.JLabel();
        lblIconTK1 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        lblIconText = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        pnlMenuSys = new javax.swing.JPanel();
        lblDoiMK = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblThoat = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pnlTitle.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTitleMouseDragged(evt);
            }
        });
        pnlTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTitleMousePressed(evt);
            }
        });

        lblClose.setBackground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_delete_15px.png"))); // NOI18N
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });

        lblMinimize.setBackground(new java.awt.Color(255, 255, 255));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_minimize_window_15px.png"))); // NOI18N
        lblMinimize.setOpaque(true);
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(lblClose)
            .addComponent(lblMinimize)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 129, 112));
        kGradientPanel2.setkStartColor(new java.awt.Color(40, 61, 90));

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.setPreferredSize(new java.awt.Dimension(70, 70));

        lblTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        lblTaiKhoan.setText("Tài khoản");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("email@gamil.com");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MAIN NAVIGATON");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("@2020 SmartBees");

        pnlDonHang.setOpaque(false);
        pnlDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDonHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDonHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDonHangMouseExited(evt);
            }
        });

        pnlColorDH.setOpaque(false);

        javax.swing.GroupLayout pnlColorDHLayout = new javax.swing.GroupLayout(pnlColorDH);
        pnlColorDH.setLayout(pnlColorDHLayout);
        pnlColorDHLayout.setHorizontalGroup(
            pnlColorDHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pnlColorDHLayout.setVerticalGroup(
            pnlColorDHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblIconDH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconDH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_purchase_order_32px.png"))); // NOI18N

        lblTextDH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTextDH.setForeground(new java.awt.Color(255, 255, 255));
        lblTextDH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextDH.setText("Đơn hàng");

        javax.swing.GroupLayout pnlDonHangLayout = new javax.swing.GroupLayout(pnlDonHang);
        pnlDonHang.setLayout(pnlDonHangLayout);
        pnlDonHangLayout.setHorizontalGroup(
            pnlDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDonHangLayout.createSequentialGroup()
                .addComponent(pnlColorDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIconDH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTextDH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconDH1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        pnlDonHangLayout.setVerticalGroup(
            pnlDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlColorDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIconDH, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(lblTextDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIconDH1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlLoai.setOpaque(false);
        pnlLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLoaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlLoaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlLoaiMouseExited(evt);
            }
        });

        pnlColorL.setOpaque(false);

        javax.swing.GroupLayout pnlColorLLayout = new javax.swing.GroupLayout(pnlColorL);
        pnlColorL.setLayout(pnlColorLLayout);
        pnlColorLLayout.setHorizontalGroup(
            pnlColorLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pnlColorLLayout.setVerticalGroup(
            pnlColorLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblIconL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_product_32px.png"))); // NOI18N

        lblTextL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTextL.setForeground(new java.awt.Color(255, 255, 255));
        lblTextL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextL.setText("Loại");

        javax.swing.GroupLayout pnlLoaiLayout = new javax.swing.GroupLayout(pnlLoai);
        pnlLoai.setLayout(pnlLoaiLayout);
        pnlLoaiLayout.setHorizontalGroup(
            pnlLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaiLayout.createSequentialGroup()
                .addComponent(pnlColorL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIconL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTextL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconL1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        pnlLoaiLayout.setVerticalGroup(
            pnlLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlColorL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIconL, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(lblTextL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIconL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlNhaCC.setOpaque(false);
        pnlNhaCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNhaCCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNhaCCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNhaCCMouseExited(evt);
            }
        });

        pnlColorNCC.setOpaque(false);

        javax.swing.GroupLayout pnlColorNCCLayout = new javax.swing.GroupLayout(pnlColorNCC);
        pnlColorNCC.setLayout(pnlColorNCCLayout);
        pnlColorNCCLayout.setHorizontalGroup(
            pnlColorNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pnlColorNCCLayout.setVerticalGroup(
            pnlColorNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblIconNCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_supplier_32px.png"))); // NOI18N

        lblTextNCC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTextNCC.setForeground(new java.awt.Color(255, 255, 255));
        lblTextNCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextNCC.setText("Nhà cung cấp");

        javax.swing.GroupLayout pnlNhaCCLayout = new javax.swing.GroupLayout(pnlNhaCC);
        pnlNhaCC.setLayout(pnlNhaCCLayout);
        pnlNhaCCLayout.setHorizontalGroup(
            pnlNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhaCCLayout.createSequentialGroup()
                .addComponent(pnlColorNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIconNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTextNCC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconNCC1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        pnlNhaCCLayout.setVerticalGroup(
            pnlNhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlColorNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIconNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(lblTextNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIconNCC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlSanPham.setOpaque(false);
        pnlSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSanPhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSanPhamMouseExited(evt);
            }
        });

        pnlColorSP.setOpaque(false);

        javax.swing.GroupLayout pnlColorSPLayout = new javax.swing.GroupLayout(pnlColorSP);
        pnlColorSP.setLayout(pnlColorSPLayout);
        pnlColorSPLayout.setHorizontalGroup(
            pnlColorSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pnlColorSPLayout.setVerticalGroup(
            pnlColorSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblIconSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_trolley_32px.png"))); // NOI18N

        lblTextSP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTextSP.setForeground(new java.awt.Color(255, 255, 255));
        lblTextSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextSP.setText("Sản phẩm");

        javax.swing.GroupLayout pnlSanPhamLayout = new javax.swing.GroupLayout(pnlSanPham);
        pnlSanPham.setLayout(pnlSanPhamLayout);
        pnlSanPhamLayout.setHorizontalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSanPhamLayout.createSequentialGroup()
                .addComponent(pnlColorSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIconSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTextSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        pnlSanPhamLayout.setVerticalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlColorSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIconSP, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(lblTextSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIconSP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlKhachHang.setOpaque(false);
        pnlKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlKhachHangMouseExited(evt);
            }
        });

        pnlColorKH.setOpaque(false);

        javax.swing.GroupLayout pnlColorKHLayout = new javax.swing.GroupLayout(pnlColorKH);
        pnlColorKH.setLayout(pnlColorKHLayout);
        pnlColorKHLayout.setHorizontalGroup(
            pnlColorKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pnlColorKHLayout.setVerticalGroup(
            pnlColorKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblIconKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_user_engagement_male_32px.png"))); // NOI18N

        lblTextKH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTextKH.setForeground(new java.awt.Color(255, 255, 255));
        lblTextKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextKH.setText("Khách hàng");

        javax.swing.GroupLayout pnlKhachHangLayout = new javax.swing.GroupLayout(pnlKhachHang);
        pnlKhachHang.setLayout(pnlKhachHangLayout);
        pnlKhachHangLayout.setHorizontalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhachHangLayout.createSequentialGroup()
                .addComponent(pnlColorKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIconKH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTextKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconKH1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        pnlKhachHangLayout.setVerticalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlColorKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIconKH, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(lblTextKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIconKH1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlNhanVien.setOpaque(false);
        pnlNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseExited(evt);
            }
        });

        pnlColorNV.setOpaque(false);

        javax.swing.GroupLayout pnlColorNVLayout = new javax.swing.GroupLayout(pnlColorNV);
        pnlColorNV.setLayout(pnlColorNVLayout);
        pnlColorNVLayout.setHorizontalGroup(
            pnlColorNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pnlColorNVLayout.setVerticalGroup(
            pnlColorNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblIconNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_staff_32px.png"))); // NOI18N

        lblTextNV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTextNV.setForeground(new java.awt.Color(255, 255, 255));
        lblTextNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextNV.setText("Nhân viên");

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                .addComponent(pnlColorNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIconNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTextNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlColorNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIconNV, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(lblTextNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIconNV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlThonhKe.setOpaque(false);
        pnlThonhKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThonhKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlThonhKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlThonhKeMouseExited(evt);
            }
        });

        pnlColorTK.setOpaque(false);

        javax.swing.GroupLayout pnlColorTKLayout = new javax.swing.GroupLayout(pnlColorTK);
        pnlColorTK.setLayout(pnlColorTKLayout);
        pnlColorTKLayout.setHorizontalGroup(
            pnlColorTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pnlColorTKLayout.setVerticalGroup(
            pnlColorTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblIconTK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_bar_chart_32px.png"))); // NOI18N

        lblTextTK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTextTK.setForeground(new java.awt.Color(255, 255, 255));
        lblTextTK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextTK.setText("Thống kê");

        javax.swing.GroupLayout pnlThonhKeLayout = new javax.swing.GroupLayout(pnlThonhKe);
        pnlThonhKe.setLayout(pnlThonhKeLayout);
        pnlThonhKeLayout.setHorizontalGroup(
            pnlThonhKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThonhKeLayout.createSequentialGroup()
                .addComponent(pnlColorTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIconTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTextTK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconTK1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        pnlThonhKeLayout.setVerticalGroup(
            pnlThonhKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlColorTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIconTK, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(lblTextTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblIconTK1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnlDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlThonhKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlThonhKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 582));

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 129, 112));
        kGradientPanel1.setkGradientFocus(2000);
        kGradientPanel1.setkStartColor(new java.awt.Color(40, 61, 75));

        lblIconText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIconText.setForeground(new java.awt.Color(255, 255, 255));
        lblIconText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_home_25px.png"))); // NOI18N
        lblIconText.setText("Trang chủ");

        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_menu_25px.png"))); // NOI18N
        lblMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMenuMouseExited(evt);
            }
        });

        lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblIconText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 662, Short.MAX_VALUE)
                .addComponent(lblHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(lblIconText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 818, 30));

        pnlMenuSys.setBackground(new java.awt.Color(177, 104, 104));
        pnlMenuSys.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblDoiMK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDoiMK.setForeground(new java.awt.Color(255, 255, 255));
        lblDoiMK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_password_reset_20px_1.png"))); // NOI18N
        lblDoiMK.setText("Đổi mật khẩu");
        lblDoiMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoiMKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDoiMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDoiMKMouseExited(evt);
            }
        });

        lblDangXuat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_exit_20px_1.png"))); // NOI18N
        lblDangXuat.setText("Đăng xuất");
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        lblThoat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblThoat.setForeground(new java.awt.Color(255, 255, 255));
        lblThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_shutdown_20px_1.png"))); // NOI18N
        lblThoat.setText("Thoát");
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThoatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuSysLayout = new javax.swing.GroupLayout(pnlMenuSys);
        pnlMenuSys.setLayout(pnlMenuSysLayout);
        pnlMenuSysLayout.setHorizontalGroup(
            pnlMenuSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDoiMK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addComponent(lblDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuSysLayout.setVerticalGroup(
            pnlMenuSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuSysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDoiMK)
                .addGap(7, 7, 7)
                .addComponent(lblDangXuat)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThoat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(pnlMenuSys, new org.netbeans.lib.awtextra.AbsoluteConstraints(863, 30, 120, 0));

        pnlBody.setBackground(new java.awt.Color(255, 255, 255));
        pnlBody.setLayout(new java.awt.CardLayout());
        jPanel2.add(pnlBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 818, 552));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(MainJFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setBackground(new java.awt.Color(204, 0, 0));
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_delete_15px_1.png")));
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setBackground(new java.awt.Color(255, 255, 255));
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_delete_15px.png")));
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        lblMinimize.setBackground(new java.awt.Color(204, 204, 204));
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_minimize_window_15px_1.png")));
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setBackground(new java.awt.Color(255, 255, 255));
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_minimize_window_15px.png")));
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void pnlTitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitleMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnlTitleMousePressed

    private void pnlTitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitleMouseDragged
        int xX = evt.getXOnScreen();
        int yY = evt.getYOnScreen();

        this.setLocation(xX - x, yY - y);
    }//GEN-LAST:event_pnlTitleMouseDragged

    private void pnlDonHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDonHangMouseEntered
        this.ColorPanelEnter(pnlDonHang);
    }//GEN-LAST:event_pnlDonHangMouseEntered

    private void pnlDonHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDonHangMouseExited
        this.ColorPanelExit(pnlDonHang, lblIconDH1);
    }//GEN-LAST:event_pnlDonHangMouseExited

    private void pnlSanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSanPhamMouseEntered
        this.ColorPanelEnter(pnlSanPham);
    }//GEN-LAST:event_pnlSanPhamMouseEntered

    private void pnlSanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSanPhamMouseExited
        this.ColorPanelExit(pnlSanPham, lblIconSP1);
    }//GEN-LAST:event_pnlSanPhamMouseExited

    private void pnlKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhachHangMouseEntered
        this.ColorPanelEnter(pnlKhachHang);
    }//GEN-LAST:event_pnlKhachHangMouseEntered

    private void pnlKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhachHangMouseExited
        this.ColorPanelExit(pnlKhachHang, lblIconKH1);
    }//GEN-LAST:event_pnlKhachHangMouseExited

    private void pnlNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseEntered
        this.ColorPanelEnter(pnlNhanVien);
    }//GEN-LAST:event_pnlNhanVienMouseEntered

    private void pnlNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseExited
        this.ColorPanelExit(pnlNhanVien, lblIconNV1);
    }//GEN-LAST:event_pnlNhanVienMouseExited

    private void pnlThonhKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThonhKeMouseEntered
        this.ColorPanelEnter(pnlThonhKe);
    }//GEN-LAST:event_pnlThonhKeMouseEntered

    private void pnlThonhKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThonhKeMouseExited
        this.ColorPanelExit(pnlThonhKe, lblIconTK1);
    }//GEN-LAST:event_pnlThonhKeMouseExited

    private void pnlDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDonHangMouseClicked
        this.OtherClick();
        this.PanelClick(pnlDonHang, pnlColorDH, lblIconDH, lblTextDH,
                lblIconDH1, 250, 156, 10, "icons8_purchase_order_32px_1.png",
                "icons8_purchase_order_25px.png", "Đơn hàng");
        if (dhPanel == null) {
            pnlBody.removeAll();
            dhPanel = new DonHangJPanel();
            pnlBody.add(dhPanel);
            nvPanel = null;
            khPanel = null;
            tcPanel = null;
            spPanel = null;
            nccPanel = null;
            lPanel = null;
            tkPanel = null;
        }
    }//GEN-LAST:event_pnlDonHangMouseClicked

    private void pnlSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSanPhamMouseClicked
        this.OtherClick();
        this.PanelClick(pnlSanPham, pnlColorSP, lblIconSP, lblTextSP,
                lblIconSP1, 47, 226, 0, "icons8_trolley_32px_5.png",
                "icons8_trolley_25px.png", "Sản phẩm");
        if (spPanel == null) {
            pnlBody.removeAll();
            spPanel = new SanPhamJPanel();
            pnlBody.add(spPanel);
            nvPanel = null;
            khPanel = null;
            tcPanel = null;
            dhPanel = null;
            nccPanel = null;
            lPanel = null;
            tkPanel = null;
        }
    }//GEN-LAST:event_pnlSanPhamMouseClicked

    private void pnlKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhachHangMouseClicked
        this.OtherClick();
        this.PanelClick(pnlKhachHang, pnlColorKH, lblIconKH, lblTextKH,
                lblIconKH1, 0, 222, 226, "icons8_user_engagement_male_32px_1.png",
                "icons8_user_engagement_male_25px.png", "Khách hàng");
        if (khPanel == null) {
            pnlBody.removeAll();
            khPanel = new KhachHangJPanel();
            pnlBody.add(khPanel);
            tcPanel = null;
            nvPanel = null;
            spPanel = null;
            dhPanel = null;
            nccPanel = null;
            lPanel = null;
            tkPanel = null;
        }
    }//GEN-LAST:event_pnlKhachHangMouseClicked

    private void pnlNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseClicked
        this.OtherClick();
        this.PanelClick(pnlNhanVien, pnlColorNV, lblIconNV, lblTextNV,
                lblIconNV1, 255, 231, 3, "icons8_staff_32px_1.png",
                "icons8_staff_25px.png", "Nhân viên");
        if (nvPanel == null) {
            pnlBody.removeAll();
            nvPanel = new NhanVienPanel();
            pnlBody.add(nvPanel);
            tcPanel = null;
            khPanel = null;
            spPanel = null;
            dhPanel = null;
            nccPanel = null;
            lPanel = null;
            tkPanel = null;
        }

    }//GEN-LAST:event_pnlNhanVienMouseClicked

    private void pnlThonhKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThonhKeMouseClicked
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền truy cập thống kê!");
        } else {
            this.OtherClick();
            this.PanelClick(pnlThonhKe, pnlColorTK, lblIconTK, lblTextTK,
                    lblIconTK1, 255, 129, 129, "icons8_bar_chart_32px_3.png",
                    "icons8_bar_chart_25px_2.png", "Thống kê");
            if (tkPanel == null) {
                pnlBody.removeAll();
                tkPanel = new ThongKeJPanel();
                pnlBody.add(tkPanel);
                tcPanel = null;
                khPanel = null;
                spPanel = null;
                dhPanel = null;
                nccPanel = null;
                lPanel = null;
                nvPanel = null;
            }
        }
    }//GEN-LAST:event_pnlThonhKeMouseClicked

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        lblIconText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_home_25px.png")));
        lblIconText.setText("Trang chủ");
        lblHome.setIcon(null);
        this.OtherClick();
        if (tcPanel == null) {
            pnlBody.removeAll();
            tcPanel = new TrangChuJPanel();
            pnlBody.add(tcPanel);
            nvPanel = null;
            khPanel = null;
            spPanel = null;
            dhPanel = null;
            nccPanel = null;
            lPanel = null;
            tkPanel = null;
        }
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked
        if (pnlMenuSys.getHeight() != 95) {
            timerDown.start();
        } else {
            timerUp.start();
        }
    }//GEN-LAST:event_lblMenuMouseClicked

    private void pnlLoaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLoaiMouseEntered
        this.ColorPanelEnter(pnlLoai);
    }//GEN-LAST:event_pnlLoaiMouseEntered

    private void pnlLoaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLoaiMouseExited
        this.ColorPanelExit(pnlLoai, lblIconL1);
    }//GEN-LAST:event_pnlLoaiMouseExited

    private void pnlNhaCCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhaCCMouseEntered
        this.ColorPanelEnter(pnlNhaCC);
    }//GEN-LAST:event_pnlNhaCCMouseEntered

    private void pnlNhaCCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhaCCMouseExited
        this.ColorPanelExit(pnlNhaCC, lblIconNCC1);
    }//GEN-LAST:event_pnlNhaCCMouseExited

    private void pnlLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLoaiMouseClicked
        this.OtherClick();
        this.PanelClick(pnlLoai, pnlColorL, lblIconL, lblTextL,
                lblIconL1, 249, 118, 176, "icons8_product_32px_3.png",
                "icons8_product_25px.png", "Loại");
        if (lPanel == null) {
            pnlBody.removeAll();
            lPanel = new LoaiJPanel();
            pnlBody.add(lPanel);
            nvPanel = null;
            khPanel = null;
            spPanel = null;
            dhPanel = null;
            nccPanel = null;
            tcPanel = null;
            tkPanel = null;
        }
    }//GEN-LAST:event_pnlLoaiMouseClicked

    private void pnlNhaCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhaCCMouseClicked
        this.OtherClick();
        this.PanelClick(pnlNhaCC, pnlColorNCC, lblIconNCC, lblTextNCC,
                lblIconNCC1, 253, 138, 114, "icons8_supplier_32px_2.png",
                "icons8_supplier_25px.png", "Nhà cung cấp");
        if (nccPanel == null) {
            pnlBody.removeAll();
            nccPanel = new NhaCungCapJPanel();
            pnlBody.add(nccPanel);
            nvPanel = null;
            khPanel = null;
            spPanel = null;
            dhPanel = null;
            lPanel = null;
            tcPanel = null;
            tkPanel = null;
        }
    }//GEN-LAST:event_pnlNhaCCMouseClicked

    private void lblMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseEntered
        this.ColorLabelEnter(lblMenu);
    }//GEN-LAST:event_lblMenuMouseEntered

    private void lblMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseExited
        this.ColorLabelExit(lblMenu);
    }//GEN-LAST:event_lblMenuMouseExited

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        this.ColorLabelEnter(lblHome);
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        this.ColorLabelExit(lblHome);
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblDoiMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoiMKMouseEntered
        this.ColorLabelEnter(lblDoiMK);
    }//GEN-LAST:event_lblDoiMKMouseEntered

    private void lblDoiMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoiMKMouseExited
        this.ColorLabelExit(lblDoiMK);
    }//GEN-LAST:event_lblDoiMKMouseExited

    private void lblDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseEntered
        this.ColorLabelEnter(lblDangXuat);
    }//GEN-LAST:event_lblDangXuatMouseEntered

    private void lblDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseExited
        this.ColorLabelExit(lblDangXuat);
    }//GEN-LAST:event_lblDangXuatMouseExited

    private void lblThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseEntered
        this.ColorLabelEnter(lblThoat);
    }//GEN-LAST:event_lblThoatMouseEntered

    private void lblThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseExited
        this.ColorLabelExit(lblThoat);
    }//GEN-LAST:event_lblThoatMouseExited

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
        this.logout();
    }//GEN-LAST:event_lblDangXuatMouseClicked

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        this.exit();
    }//GEN-LAST:event_lblThoatMouseClicked

    private void lblDoiMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoiMKMouseClicked
        // TODO add your handling code here:
        new DoiMatKhauJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblDoiMKMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblDoiMK;
    private static javax.swing.JLabel lblEmail;
    private static javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblIconDH;
    private javax.swing.JLabel lblIconDH1;
    private javax.swing.JLabel lblIconKH;
    private javax.swing.JLabel lblIconKH1;
    private javax.swing.JLabel lblIconL;
    private javax.swing.JLabel lblIconL1;
    private javax.swing.JLabel lblIconNCC;
    private javax.swing.JLabel lblIconNCC1;
    private javax.swing.JLabel lblIconNV;
    private javax.swing.JLabel lblIconNV1;
    private javax.swing.JLabel lblIconSP;
    private javax.swing.JLabel lblIconSP1;
    private javax.swing.JLabel lblIconTK;
    private javax.swing.JLabel lblIconTK1;
    private javax.swing.JLabel lblIconText;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMinimize;
    private static javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblTextDH;
    private javax.swing.JLabel lblTextKH;
    private javax.swing.JLabel lblTextL;
    private javax.swing.JLabel lblTextNCC;
    private javax.swing.JLabel lblTextNV;
    private javax.swing.JLabel lblTextSP;
    private javax.swing.JLabel lblTextTK;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlColorDH;
    private javax.swing.JPanel pnlColorKH;
    private javax.swing.JPanel pnlColorL;
    private javax.swing.JPanel pnlColorNCC;
    private javax.swing.JPanel pnlColorNV;
    private javax.swing.JPanel pnlColorSP;
    private javax.swing.JPanel pnlColorTK;
    private javax.swing.JPanel pnlDonHang;
    private javax.swing.JPanel pnlKhachHang;
    private javax.swing.JPanel pnlLoai;
    private javax.swing.JPanel pnlMenuSys;
    private javax.swing.JPanel pnlNhaCC;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlSanPham;
    private javax.swing.JPanel pnlThonhKe;
    private javax.swing.JPanel pnlTitle;
    // End of variables declaration//GEN-END:variables

    int x, y;
    private TrangChuJPanel tcPanel;
    private NhanVienPanel nvPanel;
    private KhachHangJPanel khPanel;
    private SanPhamJPanel spPanel;
    private DonHangJPanel dhPanel;
    private NhaCungCapJPanel nccPanel;
    private LoaiJPanel lPanel;
    private ThongKeJPanel tkPanel;

    private void init() {
        setSize(1000, 600);
        setIconImage(Ximage.APP_ICON);
        setLocationRelativeTo(null);
        tcPanel = new TrangChuJPanel();
        pnlBody.add(tcPanel);
        this.openWelcome();
        this.openLogin();
        lblEmail.setText(Auth.User.getEmail());
    }

    private void ColorPanelEnter(JPanel panel) {
        panel.setOpaque(true);
        panel.setBackground(new java.awt.Color(83, 140, 150));
    }

    private void ColorPanelExit(JPanel panel, JLabel lblIcon1) {
        if (lblIcon1.getIcon() == null) {
            panel.setOpaque(false);
            panel.setBackground(new java.awt.Color(240, 240, 240));
        }
    }

    private void PanelClick(JPanel pnl, JPanel pnlColor, JLabel lblIcon, JLabel lblText,
            JLabel lblIcon1, int x, int y, int z, String nameIcon, String IconTitle, String title) {
        pnl.setOpaque(true);
        pnl.setBackground(new java.awt.Color(83, 140, 150));
        pnlColor.setOpaque(true);
        pnlColor.setBackground(new java.awt.Color(x, y, z));
        lblIcon.setIcon(null);
        lblText.setForeground(new java.awt.Color(x, y, z));
        lblIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/" + nameIcon)));
        lblIconText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/" + IconTitle)));
        lblIconText.setText(title);
        if (!lblIconText.getText().equals("Trang chủ")) {
            lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_home_25px.png")));
        }
    }

    private void RsPanelClick(JPanel pnl, JPanel pnlColor, JLabel lblIcon, JLabel lblText,
            JLabel lblIcon1, String nameIcon) {
        pnl.setOpaque(false);
        pnl.setBackground(new java.awt.Color(240, 240, 240));
        pnlColor.setOpaque(false);
        pnlColor.setBackground(new java.awt.Color(240, 240, 240));
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/" + nameIcon)));
        lblText.setForeground(new java.awt.Color(255, 255, 255));
        lblIcon1.setIcon(null);
    }

    private void ColorLabelEnter(JLabel label) {
        label.setOpaque(true);
        label.setBackground(new java.awt.Color(83, 140, 150));
    }

    private void ColorLabelExit(JLabel label) {
        label.setOpaque(false);
        label.setBackground(new java.awt.Color(240, 240, 240));
    }

    private void OtherClick() {
        if (lblIconDH1.getIcon() != null) {
            RsPanelClick(pnlDonHang, pnlColorDH, lblIconDH, lblTextDH,
                    lblIconDH1, "icons8_purchase_order_32px.png");
        }
        if (lblIconL1.getIcon() != null) {
            RsPanelClick(pnlLoai, pnlColorL, lblIconL, lblTextL, lblIconL1,
                    "icons8_product_32px.png");
        }
        if (lblIconNCC1.getIcon() != null) {
            RsPanelClick(pnlNhaCC, pnlColorNCC, lblIconNCC, lblTextNCC,
                    lblIconNCC1, "icons8_supplier_32px.png");
        }
        if (lblIconSP1.getIcon() != null) {
            RsPanelClick(pnlSanPham, pnlColorSP, lblIconSP, lblTextSP,
                    lblIconSP1, "icons8_trolley_32px.png");
        }
        if (lblIconKH1.getIcon() != null) {
            RsPanelClick(pnlKhachHang, pnlColorKH, lblIconKH, lblTextKH,
                    lblIconKH1, "icons8_user_engagement_male_32px.png");
        }
        if (lblIconNV1.getIcon() != null) {
            RsPanelClick(pnlNhanVien, pnlColorNV, lblIconNV, lblTextNV,
                    lblIconNV1, "icons8_staff_32px.png");
        }
        if (lblIconTK1.getIcon() != null) {
            RsPanelClick(pnlThonhKe, pnlColorTK, lblIconTK, lblTextTK,
                    lblIconTK1, "icons8_bar_chart_32px.png");
        }
    }
    Timer timerDown = new Timer(30, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (pnlMenuSys.getHeight() != 95) {
                pnlMenuSys.setSize(pnlMenuSys.getWidth(), pnlMenuSys.getHeight() + 5);
            } else {
                timerDown.stop();
            }
        }
    });
    Timer timerUp = new Timer(30, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (pnlMenuSys.getHeight() > 0) {
                pnlMenuSys.setSize(pnlMenuSys.getWidth(), pnlMenuSys.getHeight() - 5);
            } else {
                timerUp.stop();
            }
        }
    });

    void openWelcome() {
        new ChaoJDialog(this, true).setVisible(true);
    }

    void openLogin() {
        new DangNhapJDialog(this, true).setVisible(true);
    }

    void logout() {
        Auth.clear();
        lblIconText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoessys/icon/icons8_home_25px.png")));
        lblIconText.setText("Trang chủ");
        lblHome.setIcon(null);
        this.OtherClick();
        if (tcPanel == null) {
            pnlBody.removeAll();
            tcPanel = new TrangChuJPanel();
            pnlBody.add(tcPanel);
            nvPanel = null;
            khPanel = null;
            spPanel = null;
            dhPanel = null;
            nccPanel = null;
            lPanel = null;
            tkPanel = null;
        }
        this.openLogin();
    }

    void exit() {
        if (MsgBox.comfirm(this, "Bạn thực sự muốn thoát?")) {
            System.exit(0);
        }
    }
}
