/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shoessys.ui;

import com.shoessys.dao.ThongKeDAO;
import java.awt.Color;
import java.text.NumberFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author trann
 */
public class TKDoanhThuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TKDoanhThuJPanel
     */
    public TKDoanhThuJPanel() {
        initComponents();
    }
    public TKDoanhThuJPanel(String time, Date ngaybd, Date ngaykt) {
        initComponents();
        fillChart(time, ngaybd, ngaykt);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoanhThu = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        pnlChart = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        tblDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NĂM", "DOANH THU"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoanhThu.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblDoanhThu);

        pnlChart.setBackground(new java.awt.Color(255, 255, 255));
        pnlChart.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator1)
            .addComponent(pnlChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlChart, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JPanel pnlChart;
    public static javax.swing.JTable tblDoanhThu;
    // End of variables declaration//GEN-END:variables
    static ThongKeDAO dao = new ThongKeDAO();
    static Locale vn = new Locale("vi", "VN");
    static NumberFormat VND = NumberFormat.getCurrencyInstance(vn);
    public static JFreeChart chart;
    
    static void fillChart(String time, Date ngaybd, Date ngaykt){
        List<Object[]> list = dao.getDoanhThuNam(ngaybd, ngaykt);
        DefaultTableModel model = (DefaultTableModel)tblDoanhThu.getModel();
        model.setColumnIdentifiers(new Object[]{"NĂM", "DOANH THU"});
        if(time.equals("Tháng")){
            list = dao.getDoanhThuThang(ngaybd, ngaykt);
            model.setColumnIdentifiers(new Object[]{"THÁNG", "DOANH THU"});
        }
        model.setRowCount(0);
        DefaultCategoryDataset data = new DefaultCategoryDataset();
        if(time.equals("Tháng")){
            for(Object[] sp:list){
                data.setValue((double)sp[2], "Doanh thu", (Comparable) sp[1]+"/"+sp[0]);
                model.addRow(new Object[]{sp[1]+"/"+sp[0], VND.format(sp[2]).replace("đ", "")});
            }
            chart = ChartFactory.createLineChart("TK Doanh thu", 
                "Tháng", "Doanh thu", data, PlotOrientation.VERTICAL, false, true, false);
        }else{
            for(Object[] sp:list){
                data.setValue((double)sp[1], "Doanh thu", (Comparable) sp[0]);
                model.addRow(new Object[]{sp[0], VND.format(sp[1]).replace("đ", "")});
            }
            chart = ChartFactory.createLineChart("TK Doanh thu", 
                "Năm", "Doanh thu", data, PlotOrientation.VERTICAL, false, true, false);
        }
        CategoryPlot pot = chart.getCategoryPlot();

        pot.setRangeGridlinePaint(Color.black);
        pnlChart.removeAll();
        pnlChart.add(new ChartPanel(chart));
        pnlChart.updateUI();
    }
}
