/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shoessys.ui;

import com.shoessys.dao.ThongKeDAO;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author trann
 */
public class TKSanPhamJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TKSanPhamJPanel
     */
    public TKSanPhamJPanel() {
        initComponents();
    }
    
    public TKSanPhamJPanel(String time, Date ngaybd, Date ngaykt) {
        initComponents();
        fillChart(time, ngaybd, ngaykt);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        pnlChart = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NĂM", "SỐ LƯỢNG BÁN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.setGridColor(new java.awt.Color(255, 255, 255));
        tblSanPham.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblSanPham.setSelectionBackground(new java.awt.Color(83, 140, 150));
        jScrollPane1.setViewportView(tblSanPham);

        pnlChart.setBackground(new java.awt.Color(255, 255, 255));
        pnlChart.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(pnlChart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlChart, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JPanel pnlChart;
    public static javax.swing.JTable tblSanPham;
    // End of variables declaration//GEN-END:variables
    static ThongKeDAO dao = new ThongKeDAO();
    public static JFreeChart chart;
    static void fillChart(String time, Date ngaybd, Date ngaykt){
        List<Object[]> list = dao.getSanPhamNam(ngaybd, ngaykt);
        DefaultTableModel model = (DefaultTableModel)tblSanPham.getModel();
        model.setColumnIdentifiers(new Object[]{"NĂM", "SỐ LƯỢNG BÁN"});
        if(time.equals("Tháng")){
            list = dao.getSanPhamThang(ngaybd, ngaykt);
            model.setColumnIdentifiers(new Object[]{"TÊN SẢN PHẨM", "SỐ LƯỢNG BÁN"});
        }
        model.setRowCount(0);
        DefaultCategoryDataset data = new DefaultCategoryDataset();
        for(Object[] sp:list){
            data.setValue((Number) sp[1], "Số lượng", (Comparable) sp[0]);
            model.addRow(new Object[]{sp[0], sp[1]});
        }
        chart = ChartFactory.createBarChart3D("TK sản phẩm", 
                "Năm", "số lượng bán", data, PlotOrientation.VERTICAL, true, true, false);
        if(time.equals("Tháng")){
            chart = ChartFactory.createBarChart3D("TK sản phẩm", 
                "Tên sản phẩm", "số lượng bán", data, PlotOrientation.VERTICAL, true, true, false);
        }
        CategoryPlot pot = chart.getCategoryPlot();

        pot.setRangeGridlinePaint(Color.black);
        pnlChart.removeAll();
        pnlChart.add(new ChartPanel(chart));
        pnlChart.updateUI();
    }
    
}  
